
'use client';

import React, { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import PageTitle from '@/components/ui/page-title';
import SectionContainer from '@/components/ui/section-container';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle as ModalTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import FractalRenderer from '@/components/projects/fractal-renderer';
import Calculator3D from '@/components/projects/calculator-3d';
import SimpleTextAnimator from '@/components/projects/simple-text-animator';
import { Maximize, ExternalLink } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Carousel, CarouselContent, CarouselItem } from '@/components/ui/carousel';
import Autoplay from "embla-carousel-autoplay";


interface Project {
  id: string;
  title: string;
  imageUrls: string[]; // Changed to array
  imageAlt: string;
  imageHint: string;
  description: string;
  longDescription?: string;
  personalNote?: string;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Community';
  component?: React.ReactNode;
  externalLink?: string;
  className?: string;
}

const projectsData: Project[] = [
    {
    id: 'calculator',
    title: 'Interactive Calculator',
    imageUrls: ['https://i.imgur.com/cWI9lAG.png'],
    imageAlt: 'Interactive calculator interface',
    imageHint: 'calculator interface modern',
    description: 'A sleek, interactive calculator. Perform basic arithmetic operations and see large numbers in scientific notation.',
    longDescription: 'This project showcases a fully interactive calculator featuring a clean, modern interface. It supports basic arithmetic operations and formats very large or small numbers using scientific notation to maintain display integrity.',
    personalNote: "This was the lightest project I’ve done just a basic calculator I built mostly for practice. It’s not the kind of thing that really speaks to my heart, but it gave me a chance to play around with UI design a little and keep me intrigue. Sometimes it’s nice to take a break from the deep stuff and just create something simple and clean. Not my favorite, but definitely a useful step in the journey.",
    difficulty: 'Easy',
    component: <Calculator3D />,
  },
  {
    id: 'text-animator',
    title: 'Simple Text Animator',
    imageUrls: ['https://i.imgur.com/bPv5f6t.png'],
    imageAlt: 'Text animation tool interface',
    imageHint: 'text animation motion graphics',
    description: 'Create simple text animations like fade in/out, blink, and typewriter effects. Preview your creations instantly. Add multiple text layers and download settings or a static snapshot.',
    longDescription: 'This tool allows you to input multiple text strings, apply various animation effects globally, and see a live preview. Choose from a list of predefined animations, adjust parameters like duration or speed. You can download animation settings as JSON or a static PNG snapshot of the preview.',
    personalNote: "This project is a bit more complex than the calculator, and honestly it sounded cooler in my head when I started. I made it as a small tool for generating simple animations, mostly to use in other projects. It was fun to build and felt a little more purposeful, but it still ended up feeling a bit too simple for my taste. Still, it was a cool learning experience, and I like how it turned out in the end.",
    difficulty: 'Medium',
    component: <SimpleTextAnimator />,
  },
  {
    id: 'fractal-explorer',
    title: 'Interactive Fractal Explorer',
    imageUrls: ['https://i.imgur.com/Lq50HRe.png'],
    imageAlt: 'Abstract fractal visualization',
    imageHint: 'fractal abstract math visualization',
    description: 'Dive into the infinite complexity of fractals. Explore mesmerizing patterns generated by mathematical formulas and adjust rendering parameters.',
    longDescription: 'This interactive tool allows you to explore the Mandelbrot set, a classic example of a fractal. You can zoom, pan (by clicking), adjust the number of iterations to control detail, and switch between different color schemes to visualize the mathematical beauty in diverse ways. Higher iterations reveal more intricate patterns but require more computation.',
    personalNote: 'This one’s my favorite by far. It hits that level of complexity and uniqueness that I really enjoy and maybe even look for in people, too. There’s something about the way fractals build beauty out of patterns and depth that just feels meaningful to me. It’s definitely not perfect, but honestly, that makes me like it even more. It’s personal. A bit messy, a bit complex, but something I really poured myself into.',
    difficulty: 'Hard',
    component: <FractalRenderer />,
  },
  {
    id: 'silent-horizon',
    title: 'Silent Horizon',
    imageUrls: [
        'https://picsum.photos/seed/minecraft1/800/450',
        'https://picsum.photos/seed/minecraft2/800/450',
        'https://picsum.photos/seed/minecraft3/800/450',
    ],
    imageAlt: 'Silent Horizon Minecraft Server',
    imageHint: 'minecraft landscape castle',
    description: 'A Balkan Minecraft server community project with Survival, Skyblock, and Prison modes. Open for everyone to join and play.',
    difficulty: 'Community',
    externalLink: 'https://silent-horizon.com/',
    personalNote: "Honestly, this project isn't my favorite, as it was mostly done for friends. While it's a cool project that has a lot to offer—like Survival, Skyblock, and Prison game modes—it can also be incredibly draining. Managing a team of 10 staff members, keeping the community engaged, and rolling out regular events and updates is a huge undertaking. It was a massive learning experience in community management and server infrastructure, and it's awesome seeing people enjoy it, but it's not where my personal passion lies.",
    className: 'lg:col-span-3', // Span 3 columns on large screens
  },
];

export default function ProjectsPage() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  const openModal = (project: Project) => {
    if (project.externalLink && project.id === 'silent-horizon') return; // Click handled by Link component for this specific project
    if (project.externalLink) {
        window.open(project.externalLink, '_blank', 'noopener,noreferrer');
        return;
    }
    setSelectedProject(project);
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
    setTimeout(() => { 
      setSelectedProject(null);
    }, 300);
  };

  const getDifficultyBadgeVariant = (difficulty: Project['difficulty']) => {
    switch (difficulty) {
      case 'Easy':
        return 'default'; 
      case 'Medium':
        return 'secondary';
      case 'Hard':
        return 'destructive';
      case 'Community':
        return 'outline';
      default:
        return 'outline';
    }
  };

  return (
    <SectionContainer>
      <PageTitle subtitle="Explore a selection of my creative and technical projects. Click a project to learn more and interact.">
        My Projects
      </PageTitle>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-12">
        {projectsData.map((project, index) => {
          if (project.id === 'silent-horizon') {
            return (
              <div key={project.id} className={cn("flex flex-col gap-8 h-full", project.className)}>
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-center">
                  {/* Carousel Card */}
                  <div className="lg:col-span-2">
                    <Card
                      className="bg-card border-border rounded-lg overflow-hidden shadow-lg hover:shadow-primary/40 transition-all duration-300 ease-in-out group flex flex-col h-full"
                    >
                      <Carousel
                        plugins={[Autoplay({ delay: 4000, stopOnInteraction: true })]}
                        className="w-full"
                        opts={{ loop: true }}
                      >
                        <CarouselContent>
                          {project.imageUrls.map((url, i) => (
                            <CarouselItem key={i}>
                                <Link href={project.externalLink || '#'} target="_blank" rel="noopener noreferrer" className="block relative w-full overflow-hidden rounded-t-lg aspect-video">
                                  <Image
                                    src={url}
                                    alt={`${project.imageAlt} #${i + 1}`}
                                    fill
                                    sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
                                    className="object-cover"
                                    data-ai-hint={project.imageHint}
                                  />
                                </Link>
                            </CarouselItem>
                          ))}
                        </CarouselContent>
                      </Carousel>
                      
                       <CardHeader className="pb-3 pt-4 px-4">
                        <div className="flex justify-between items-start mb-1">
                          <CardTitle className="text-xl font-semibold text-foreground">{project.title}</CardTitle>
                          <Badge variant={getDifficultyBadgeVariant(project.difficulty)} className="ml-2 shrink-0">
                            {project.difficulty}
                          </Badge>
                        </div>
                      </CardHeader>
                      <CardContent className="flex-grow px-4 pb-4">
                        <CardDescription className="text-muted-foreground text-sm line-clamp-3 mb-3">{project.description}</CardDescription>
                      </CardContent>
                      <CardFooter className="mt-auto pt-2 px-4 pb-4">
                        <Button asChild variant="outline" className="w-full">
                           <Link href={project.externalLink || '#'} target="_blank" rel="noopener noreferrer">
                            <ExternalLink className="mr-2 h-4 w-4" /> Visit Site
                           </Link>
                        </Button>
                      </CardFooter>
                    </Card>
                  </div>
                  
                  {/* Personal Note Card */}
                  {project.personalNote && (
                    <div className="lg:col-span-1">
                       <Card className="bg-card border-border/70 shadow-md rounded-lg w-full flex flex-col">
                        <CardHeader className="pb-2 pt-4 px-4">
                          <CardTitle className="text-base font-medium text-foreground/90">
                            My Opinion
                          </CardTitle>
                        </CardHeader>
                        <CardContent className="px-4 pb-4 pt-0 flex-grow flex items-center">
                          <p className="text-sm text-muted-foreground">{project.personalNote}</p>
                        </CardContent>
                      </Card>
                    </div>
                  )}
                </div>
              </div>
            );
          }
          
          return (
            <Dialog key={project.id} open={selectedProject?.id === project.id && isModalOpen} onOpenChange={(open) => {
              if (!open) closeModal();
            }}>
              <div className={cn("flex flex-col gap-4 h-full", project.className)}> 
                <DialogTrigger asChild>
                  <Card
                    className="bg-card border-border rounded-lg overflow-hidden shadow-lg hover:shadow-primary/40 transition-all duration-300 ease-in-out cursor-pointer group flex flex-col h-full"
                    onClick={() => openModal(project)}
                    role="button"
                    tabIndex={0}
                    onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && openModal(project)}
                    aria-label={`Explore project: ${project.title}`}
                  >
                    <div className="relative w-full overflow-hidden rounded-t-lg aspect-video">
                      <Image
                        src={project.imageUrls[0]}
                        alt={project.imageAlt}
                        fill
                        sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
                        className="object-cover"
                        data-ai-hint={project.imageHint}
                        priority={index < 2}
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-4">
                        <Button variant="secondary" size="sm" className="pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-100 translate-y-2 group-hover:translate-y-0">
                          {project.externalLink ? <ExternalLink className="mr-2 h-4 w-4" /> : <Maximize className="mr-2 h-4 w-4" />}
                          {project.externalLink ? 'Visit Site' : 'Explore'}
                        </Button>
                      </div>
                    </div>
                    <CardHeader className="pb-3 pt-4 px-4">
                      <div className="flex justify-between items-start mb-1">
                        <CardTitle className="text-xl font-semibold text-foreground">{project.title}</CardTitle>
                        <Badge variant={getDifficultyBadgeVariant(project.difficulty)} className="ml-2 shrink-0">
                          {project.difficulty}
                        </Badge>
                      </div>
                    </CardHeader>
                    <CardContent className="flex-grow px-4 pb-4">
                      <CardDescription className="text-muted-foreground text-sm line-clamp-3 mb-3">{project.description}</CardDescription>
                    </CardContent>
                    <CardFooter className="mt-auto pt-2 px-4 pb-4">
                      {/* Placeholder for future actions or links if needed */}
                    </CardFooter>
                  </Card>
                </DialogTrigger>
                
                {project.personalNote && (
                  <Card className="bg-card border-border/70 shadow-md rounded-lg">
                    <CardHeader className="pb-2 pt-4 px-4">
                      <CardTitle className="text-base font-medium text-foreground/90">
                        {project.id === 'calculator' || project.id === 'text-animator' || project.id === 'fractal-explorer' ? 'My Opinion' : 'Developer Insights'}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="px-4 pb-4 pt-0">
                      <p className="text-sm text-muted-foreground">{project.personalNote}</p>
                    </CardContent>
                  </Card>
                )}
              </div>

              {selectedProject?.id === project.id && (
                <DialogContent
                  hideDefaultClose={true}
                  className="p-0 bg-background border-border shadow-2xl rounded-lg flex flex-col items-center justify-center w-[95vw] max-w-4xl h-[90vh] overflow-hidden data-[state=open]:animate-fade-in-slow data-[state=closed]:animate-fade-out-slow"
                >
                  <DialogHeader className="p-4 border-b border-border w-full flex flex-row justify-between items-center">
                    <ModalTitle className="sr-only">{selectedProject.title}</ModalTitle>
                    {/* Removed the custom close button from here */}
                  </DialogHeader>
                  <div className="flex flex-grow w-full h-full items-center justify-center p-0 sm:p-4 overflow-y-auto bg-background">
                    {selectedProject.component}
                  </div>
                  {selectedProject.longDescription && <div className="p-4 border-t border-border w-full bg-card">
                      <p className="text-sm text-muted-foreground">{selectedProject.longDescription}</p>
                  </div>}
                </DialogContent>
              )}
            </Dialog>
          )
        })}
      </div>
       <style jsx global>{`
        @keyframes fade-in-slow {
          from { opacity: 0; transform: scale(0.95) translateY(10px); }
          to { opacity: 1; transform: scale(1) translateY(0); }
        }
        .data-\\[state=open\\]_animate-fade-in-slow {
          animation: fade-in-slow 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }
        @keyframes fade-out-slow {
          from { opacity: 1; transform: scale(1) translateY(0); }
          to { opacity: 0; transform: scale(0.95) translateY(10px); }
        }
        .data-\\[state=closed\\]_animate-fade-out-slow {
          animation: fade-out-slow 0.5s cubic-bezier(0.7, 0, 0.84, 0) forwards;
        }
      `}</style>
    </SectionContainer>
  );
}
