
'use client';

import React, { useState } from 'react';
import Image from 'next/image';
import PageTitle from '@/components/ui/page-title';
import SectionContainer from '@/components/ui/section-container';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle as ModalTitle, DialogClose } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import FractalRenderer from '@/components/projects/fractal-renderer';
import Calculator3D from '@/components/projects/calculator-3d';
import SimpleTextAnimator from '@/components/projects/simple-text-animator'; // New Import
import { Maximize, X as LucideX } from 'lucide-react';

interface Project {
  id: string;
  title: string;
  imageUrl: string;
  imageAlt: string;
  imageHint: string;
  description: string;
  longDescription: string;
}

const projectsData: Project[] = [
  {
    id: 'fractal-explorer',
    title: 'Interactive Fractal Explorer',
    imageUrl: 'https://placehold.co/800x600.png',
    imageAlt: 'Abstract fractal visualization',
    imageHint: 'fractal abstract',
    description: 'Dive into the infinite complexity of fractals. Explore mesmerizing patterns generated by mathematical formulas and adjust rendering parameters.',
    longDescription: 'This interactive tool allows you to explore the Mandelbrot set, a classic example of a fractal. You can zoom, pan (by clicking), adjust the number of iterations to control detail, and switch between different color schemes to visualize the mathematical beauty in diverse ways. Higher iterations reveal more intricate patterns but require more computation.',
  },
  {
    id: 'calculator',
    title: 'Interactive Calculator',
    imageUrl: 'https://placehold.co/800x600.png',
    imageAlt: 'Stylized calculator interface',
    imageHint: 'calculator interface',
    description: 'A sleek, interactive calculator with a modern design. Perform basic arithmetic operations and see large numbers in scientific notation.',
    longDescription: 'This project showcases a fully interactive calculator featuring a clean, modern interface. It supports basic arithmetic operations and formats very large or small numbers using scientific notation to maintain display integrity.',
  },
  {
    id: 'text-animator', // Changed Project ID
    title: 'Simple Text Animator',
    imageUrl: 'https://placehold.co/800x600.png',
    imageAlt: 'Text animation tool interface',
    imageHint: 'text animation motion',
    description: 'Create simple text animations like fade in/out, blink, and typewriter effects. Preview your creations instantly.',
    longDescription: 'This tool allows you to input text and apply various animation effects. Choose from a list of predefined animations, adjust parameters like duration or speed, and see a live preview. The download feature is currently a placeholder.',
  }
];

export default function ProjectsPage() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  const openModal = (project: Project) => {
    setSelectedProject(project);
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
    setTimeout(() => { // Allow animation to finish
      setSelectedProject(null);
    }, 300);
  };

  return (
    <SectionContainer>
      <PageTitle subtitle="Explore a selection of my creative and technical projects.">
        My Projects
      </PageTitle>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {projectsData.map((project) => (
          <Dialog key={project.id} open={selectedProject?.id === project.id && isModalOpen} onOpenChange={(open) => {
            if (!open) closeModal();
          }}>
            <DialogTrigger asChild>
              <Card
                className="bg-card border-border rounded-lg overflow-hidden shadow-lg hover:shadow-primary/40 transition-all duration-300 ease-in-out cursor-pointer group flex flex-col h-full"
                onClick={() => openModal(project)}
                role="button"
                tabIndex={0}
                onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && openModal(project)}
                aria-label={`Explore project: ${project.title}`}
              >
                <div className="relative w-full aspect-[16/9] overflow-hidden">
                  <Image
                    src={project.imageUrl}
                    alt={project.imageAlt}
                    fill
                    className="object-cover group-hover:scale-105 transition-transform duration-500 ease-in-out"
                    data-ai-hint={project.imageHint}
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                    crossOrigin="anonymous"
                  />
                   <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-4">
                    <Button variant="secondary" size="sm" className="pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-100 translate-y-2 group-hover:translate-y-0">
                      <Maximize className="mr-2 h-4 w-4" /> Explore
                    </Button>
                  </div>
                </div>
                <CardHeader className="flex-grow">
                  <CardTitle className="text-xl font-semibold text-foreground mb-1">{project.title}</CardTitle>
                  <CardDescription className="text-muted-foreground text-sm line-clamp-3">{project.description}</CardDescription>
                </CardHeader>
              </Card>
            </DialogTrigger>
            {selectedProject?.id === project.id && (
              <DialogContent
                hideDefaultClose={true}
                className="p-0 bg-background border-border shadow-2xl rounded-lg flex flex-col items-center justify-center w-[95vw] max-w-4xl h-[90vh] overflow-hidden data-[state=open]:animate-fade-in-slow data-[state=closed]:animate-fade-out-slow"
              >
                <DialogHeader className="p-4 border-b border-border w-full flex flex-row justify-center items-center relative">
                  <ModalTitle className="text-2xl text-foreground text-center flex-grow mx-12 truncate sr-only">{selectedProject.title}</ModalTitle>
                  <DialogClose asChild>
                    <Button variant="ghost" size="icon" className="text-muted-foreground hover:text-foreground absolute right-1/2 top-1/2 -translate-y-1/2 translate-x-1/2" onClick={closeModal}>
                      <LucideX className="h-6 w-6" />
                      <span className="sr-only">Close</span>
                    </Button>
                  </DialogClose>
                </DialogHeader>
                <div className="flex-grow w-full h-full p-0 sm:p-4 overflow-y-auto bg-background">
                  {project.id === 'fractal-explorer' && <FractalRenderer />}
                  {project.id === 'calculator' && <Calculator3D />}
                  {project.id === 'text-animator' && <SimpleTextAnimator />}
                </div>
                 <div className="p-4 border-t border-border w-full bg-card">
                    <p className="text-sm text-muted-foreground">{selectedProject.longDescription}</p>
                </div>
              </DialogContent>
            )}
          </Dialog>
        ))}
      </div>
       <style jsx global>{`
        @keyframes fade-in-slow {
          from { opacity: 0; transform: scale(0.95) translateY(10px); }
          to { opacity: 1; transform: scale(1) translateY(0); }
        }
        .data-\\[state=open\\]_animate-fade-in-slow {
          animation: fade-in-slow 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }
        @keyframes fade-out-slow {
          from { opacity: 1; transform: scale(1) translateY(0); }
          to { opacity: 0; transform: scale(0.95) translateY(10px); }
        }
        .data-\\[state=closed\\]_animate-fade-out-slow {
          animation: fade-out-slow 0.5s cubic-bezier(0.7, 0, 0.84, 0) forwards;
        }
      `}</style>
    </SectionContainer>
  );
}
