
'use client';

import React, { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import PageTitle from '@/components/ui/page-title';
import SectionContainer from '@/components/ui/section-container';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle as ModalTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import FractalRenderer from '@/components/projects/fractal-renderer';
import Calculator3D from '@/components/projects/calculator-3d';
import SimpleTextAnimator from '@/components/projects/simple-text-animator';
import { Maximize, ExternalLink, X } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from '@/components/ui/carousel';
import Autoplay from "embla-carousel-autoplay";

interface Project {
  id: string;
  title: string;
  imageUrls: string[];
  imageAlt: string;
  imageHint: string;
  description: string;
  longDescription?: string;
  personalNote: string;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Community';
  component?: React.ReactNode;
  externalLink?: string;
}

const projectsData: Project[] = [
  {
    id: 'calculator',
    title: 'Interactive Calculator',
    imageUrls: ['https://i.imgur.com/cWI9lAG.png'],
    imageAlt: 'Interactive calculator interface',
    imageHint: 'calculator interface modern',
    description: 'A sleek, interactive calculator. Perform basic arithmetic operations and see large numbers in scientific notation.',
    longDescription: 'This project showcases a fully interactive calculator featuring a clean, modern interface. It supports basic arithmetic operations and formats very large or small numbers using scientific notation to maintain display integrity.',
    personalNote: "This was the lightest project I’ve done—just a basic calculator I built mostly for practice. It gave me a chance to play around with UI design and keep intrigued. Sometimes it’s nice to take a break from the deep stuff and just create something simple and clean.",
    difficulty: 'Easy',
    component: <Calculator3D />,
  },
  {
    id: 'text-animator',
    title: 'Simple Text Animator',
    imageUrls: ['https://i.imgur.com/bPv5f6t.png'],
    imageAlt: 'Text animation tool interface',
    imageHint: 'text animation motion graphics',
    description: 'Create simple text animations like fade in/out, blink, and typewriter effects. Preview your creations instantly.',
    longDescription: 'This tool allows you to input multiple text strings, apply various animation effects globally, and see a live preview. Choose from a list of predefined animations, adjust parameters like duration or speed.',
    personalNote: "This project is a bit more complex than the calculator, and honestly, it sounded cooler in my head when I started. It was fun to build and felt a little more purposeful, but it still ended up feeling a bit too simple for my taste. Still, it was a cool learning experience.",
    difficulty: 'Medium',
    component: <SimpleTextAnimator />,
  },
  {
    id: 'fractal-explorer',
    title: 'Interactive Fractal Explorer',
    imageUrls: ['https://i.imgur.com/Lq50HRe.png'],
    imageAlt: 'Abstract fractal visualization',
    imageHint: 'fractal abstract math visualization',
    description: 'Dive into the infinite complexity of fractals. Explore mesmerizing patterns generated by mathematical formulas.',
    longDescription: 'This interactive tool allows you to explore the Mandelbrot set, a classic example of a fractal. You can zoom, pan, adjust iterations for detail, and switch color schemes to visualize the mathematical beauty. Higher iterations reveal more intricate patterns but require more computation.',
    personalNote: 'This one’s my favorite by far. It hits that level of complexity and uniqueness that I really enjoy. There’s something about the way fractals build beauty out of patterns and depth that just feels meaningful to me. It’s definitely not perfect, but that makes me like it even more.',
    difficulty: 'Hard',
    component: <FractalRenderer />,
  },
];

const communityProject: Project = {
  id: 'silent-horizon',
  title: 'Silent Horizon Community Project',
  imageUrls: [
    'https://picsum.photos/seed/sh1/1920/1080',
    'https://picsum.photos/seed/sh2/1920/1080',
    'https://picsum.photos/seed/sh3/1920/1080',
    'https://picsum.photos/seed/sh4/1920/1080',
    'https://picsum.photos/seed/sh5/1920/1080',
  ],
  imageAlt: 'Silent Horizon Minecraft Server',
  imageHint: 'minecraft landscape castle',
  description: 'A Balkan Minecraft server community project with Survival, Skyblock, and Prison modes. Open for everyone to join and play.',
  difficulty: 'Community',
  externalLink: 'https://silent-horizon.com/',
  personalNote: "Honestly, this project isn't my favorite, as it was mostly done for friends. While it's a cool project that has a lot to offer, it can also be incredibly draining. Managing a team of 10 staff members, keeping the community engaged, and rolling out regular events and updates is a huge undertaking. It was a massive learning experience in community management, but it's not where my personal passion lies.",
};

export default function ProjectsPage() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  const openModal = (project: Project) => {
    if (project.externalLink) {
        window.open(project.externalLink, '_blank', 'noopener,noreferrer');
        return;
    }
    setSelectedProject(project);
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
    setTimeout(() => {
      setSelectedProject(null);
    }, 300);
  };

  const getDifficultyBadgeVariant = (difficulty: Project['difficulty']) => {
    switch (difficulty) {
      case 'Easy': return 'default';
      case 'Medium': return 'secondary';
      case 'Hard': return 'destructive';
      case 'Community': return 'outline';
      default: return 'outline';
    }
  };

  const ProjectCard = ({ project }: { project: Project }) => (
    <Dialog open={selectedProject?.id === project.id && isModalOpen} onOpenChange={(open) => !open && closeModal()}>
      <DialogTrigger asChild>
        <Card
          className="bg-card border-border rounded-lg overflow-hidden shadow-lg hover:shadow-primary/40 transition-all duration-300 ease-in-out cursor-pointer group flex flex-col h-full"
          onClick={() => openModal(project)}
          role="button"
          tabIndex={0}
          onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && openModal(project)}
          aria-label={`Explore project: ${project.title}`}
        >
          <div className="relative w-full overflow-hidden rounded-t-lg aspect-video">
            <Image
              src={project.imageUrls[0]}
              alt={project.imageAlt}
              fill
              sizes="(max-width: 1024px) 100vw, 33vw"
              className="object-cover transition-transform duration-300 group-hover:scale-105"
              data-ai-hint={project.imageHint}
              priority={project.id !== 'silent-horizon'}
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-black/20" />
            <div className="absolute bottom-4 left-4">
              <Button variant="secondary" size="sm" className="pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-100 translate-y-2 group-hover:translate-y-0">
                {project.externalLink ? <ExternalLink className="mr-2 h-4 w-4" /> : <Maximize className="mr-2 h-4 w-4" />}
                {project.externalLink ? 'Visit Site' : 'Explore'}
              </Button>
            </div>
          </div>
          <CardContent className="p-4 flex flex-col flex-grow">
            <div className="flex justify-between items-start mb-2">
              <CardTitle className="text-lg font-semibold text-foreground">{project.title}</CardTitle>
              <Badge variant={getDifficultyBadgeVariant(project.difficulty)} className="ml-2 shrink-0">
                {project.difficulty}
              </Badge>
            </div>
            <CardDescription className="text-muted-foreground text-sm line-clamp-3 mb-3">{project.description}</CardDescription>
            <p className="text-sm text-muted-foreground font-semibold mt-auto border-l-4 border-border pl-4">{project.personalNote}</p>
          </CardContent>
        </Card>
      </DialogTrigger>

      {selectedProject?.id === project.id && !project.externalLink && (
        <DialogContent className="p-0 bg-background border-border shadow-2xl rounded-lg flex flex-col items-center justify-center w-[95vw] max-w-4xl h-[90vh] overflow-hidden data-[state=open]:animate-fade-in-slow data-[state=closed]:animate-fade-out-slow">
          <DialogHeader className="p-4 border-b border-border w-full flex flex-row justify-between items-center shrink-0">
            <ModalTitle>{selectedProject.title}</ModalTitle>
          </DialogHeader>
          <div className="w-full h-full overflow-y-auto">
            <div className="w-full flex items-center justify-center p-2 sm:p-4 bg-muted/20 h-full">
              {selectedProject.component}
            </div>
          </div>
        </DialogContent>
      )}
    </Dialog>
  );

  return (
    <SectionContainer>
      <PageTitle subtitle="Explore a selection of my creative and technical projects. Click a project to learn more or visit the site.">
        My Projects
      </PageTitle>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {projectsData.map((project) => (
          <ProjectCard key={project.id} project={project} />
        ))}
      </div>

      <div className="mt-16 pt-10 border-t border-border/50">
        <Card className="bg-card border-border rounded-lg overflow-hidden shadow-lg hover:shadow-primary/40 transition-shadow duration-300 ease-in-out group flex flex-col md:flex-row">
            <div className="md:w-1/2 lg:w-3/5 xl:w-2/3">
                <Carousel
                    plugins={[Autoplay({ delay: 4000, stopOnInteraction: true })]}
                    className="w-full h-full rounded-t-lg md:rounded-l-lg md:rounded-t-none overflow-hidden border-b md:border-b-0 md:border-r border-border"
                    opts={{ loop: true }}
                >
                    <CarouselContent className="h-full">
                        {communityProject.imageUrls.map((url, i) => (
                        <CarouselItem key={i} className="h-full">
                            <div className="block relative w-full overflow-hidden aspect-video md:aspect-auto md:h-full">
                            <Image src={url} alt={`${communityProject.imageAlt} #${i + 1}`} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" data-ai-hint={communityProject.imageHint} />
                            </div>
                        </CarouselItem>
                        ))}
                    </CarouselContent>
                    <CarouselPrevious className="absolute left-3 top-1/2 -translate-y-1/2 z-10 h-8 w-8 bg-background/60 hover:bg-background/90 text-foreground" />
                    <CarouselNext className="absolute right-3 top-1/2 -translate-y-1/2 z-10 h-8 w-8 bg-background/60 hover:bg-background/90 text-foreground" />
                </Carousel>
            </div>
          
            <div className="p-6 flex flex-col flex-grow md:w-1/2 lg:w-2/5 xl:w-1/3">
                <div className="flex justify-between items-start mb-3">
                    <CardTitle className="text-xl font-semibold text-foreground">{communityProject.title}</CardTitle>
                    <Badge variant={getDifficultyBadgeVariant(communityProject.difficulty)} className="ml-3 shrink-0">
                    {communityProject.difficulty}
                    </Badge>
                </div>
                <CardDescription className="text-muted-foreground text-sm mb-4">{communityProject.description}</CardDescription>
                <p className="text-sm text-muted-foreground font-semibold mb-6 border-l-4 border-border pl-4">{communityProject.personalNote}</p>
                <CardFooter className="p-0 mt-auto">
                    <Button asChild variant="outline" className="w-full" onClick={() => openModal(communityProject)}>
                        <Link href={communityProject.externalLink || '#'}>
                            <ExternalLink className="mr-2 h-4 w-4" /> Visit Site
                        </Link>
                    </Button>
                </CardFooter>
            </div>
        </Card>
      </div>

       <style jsx global>{`
        @keyframes fade-in-slow {
          from { opacity: 0; transform: scale(0.95) translateY(10px); }
          to { opacity: 1; transform: scale(1) translateY(0); }
        }
        .data-\\[state=open\\]_animate-fade-in-slow {
          animation: fade-in-slow 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }
        @keyframes fade-out-slow {
          from { opacity: 1; transform: scale(1) translateY(0); }
          to { opacity: 0; transform: scale(0.95) translateY(10px); }
        }
        .data-\\[state=closed\\]_animate-fade-out-slow {
          animation: fade-out-slow 0.5s cubic-bezier(0.7, 0, 0.84, 0) forwards;
        }
      `}</style>
    </SectionContainer>
  );
