
'use client';

import Link from 'next/link';
import Image from 'next/image';
import SectionContainer from '@/components/ui/section-container';
import { motion } from 'framer-motion';
import AnimateOnScroll from '@/components/ui/animate-on-scroll';
import { Button } from '@/components/ui/button';
import { ArrowRight, Mail, User, ArrowUp, Compass, Monitor } from 'lucide-react';
import ProjectShowcase from '@/components/home/project-showcase';
import FractalRenderer from '@/components/projects/fractal-renderer';
import AIImageGenerator from '@/components/projects/ai-image-generator';
import dynamic from 'next/dynamic';
import SplineShowcase from '@/components/home/spline-showcase';
import type { Spline } from '@splinetool/react-spline';
import { Card, CardContent } from '@/components/ui/card';

const SplineModel = dynamic(
  () => import('@/components/home/spline-model'),
  { 
    ssr: false,
    loading: () => <div className="bg-muted/20 w-full h-full min-h-[500px]" />,
  }
);


const featuredProjects = [
    {
      id: 'fractal-explorer',
      title: 'Interactive Fractal Explorer',
      description: 'Dive into the infinite complexity of fractals. Explore mesmerizing patterns generated by mathematical formulas and zoom into the Mandelbrot set.',
      component: <FractalRenderer />,
      technologies: [
        { name: 'React', iconSrc: '/icons/react.svg' },
        { name: 'TypeScript', iconSrc: '/icons/typescript.svg' },
        { name: 'Tailwind CSS', iconSrc: '/icons/tailwindcss.svg' },
      ],
    },
    {
      id: 'ai-image-generator',
      title: 'AI Image Generator',
      description: 'Create unique images from text prompts using generative AI. A fun way to explore the creative power of artificial intelligence.',
      component: <AIImageGenerator />,
      technologies: [
        { name: 'React', iconSrc: '/icons/react.svg' },
        { name: 'Next.js', iconSrc: '/icons/nextjs.svg' },
        { name: 'Genkit', iconSrc: '/icons/genkit.svg' },
      ],
    },
    {
      id: 'silent-horizon',
      title: 'Silent Horizon Community Project',
      description: 'A large-scale Balkan Minecraft server community project with custom plugins, multiple game modes, and a dedicated staff team.',
      imageUrl: '/sh1.jpg',
      imageHint: 'minecraft landscape castle',
      technologies: [
          { name: 'Java', iconSrc: '/icons/java.svg' },
          { name: 'Pterodactyl', iconSrc: '/icons/pterodactyl.svg' },
          { name: 'MySQL', iconSrc: '/icons/mysql.svg' },
          { name: 'Docker', iconSrc: '/icons/docker.svg' },
          { name: 'Firebase', iconSrc: '/icons/firebase.svg' },
          { name: 'React', iconSrc: '/icons/react.svg' },
      ],
    },
];

const technologies = [
  { name: 'React', href: 'https://react.dev/', iconSrc: '/icons/react.svg' },
  { name: 'C++', href: 'https://isocpp.org/', iconSrc: '/icons/cplusplus.svg' },
  { name: 'Tailwind CSS', href: 'https://tailwindcss.com/', iconSrc: '/icons/tailwindcss.svg' },
  { name: 'Node.js', href: 'https://nodejs.org/', iconSrc: '/icons/nodejs.svg' },
  { name: 'TypeScript', href: 'https://www.typescriptlang.org/', iconSrc: '/icons/typescript.svg' },
  { name: 'Firebase', href: 'https://firebase.google.com/', iconSrc: '/icons/firebase.svg' },
  { name: 'Genkit', href: 'https://firebase.google.com/docs/genkit', iconSrc: '/icons/genkit.svg' },
  { name: 'Java', href: 'https://www.java.com/', iconSrc: '/icons/java.svg' },
  { name: 'C#', href: 'https://docs.microsoft.com/en-us/dotnet/csharp/', iconSrc: '/icons/csharp.svg' },
  { name: 'Python', href: 'https://www.python.org/', iconSrc: '/icons/python.svg' },
  { name: 'JavaScript', href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', iconSrc: '/icons/javascript.svg' },
  { name: 'Docker', href: 'https://www.docker.com/', iconSrc: '/icons/docker.svg'},
  { name: 'Webflow', href: 'https://webflow.com/', iconSrc: '/icons/webflow.svg' },
];

const splineModels = [
    { url: 'https://prod.spline.design/FfjWOhoEErL5Sia2/scene.splinecode', title: 'Cyberpunk Room', scrollable: true },
    { url: 'https://prod.spline.design/Oy8cFTtrLNL36Qll/scene.splinecode', title: 'Cozy Living Room', scrollable: true },
    { url: 'https://prod.spline.design/qC2WtYn7OhOcS8L0/scene.splinecode', title: 'Abstract Shapes', scrollable: true },
    { url: 'https://prod.spline.design/3SU82luCTBxFgmZk/scene.splinecode', title: 'Gaming Setup', scrollable: true },
];

const ScrollingTechRow = ({ items, direction = 'left' }: { items: typeof technologies, direction?: 'left' | 'right' }) => (
    <div className="w-full inline-flex flex-nowrap overflow-hidden [mask-image:_linear-gradient(to_right,transparent_0,_black_128px,_black_calc(100%-128px),transparent_100%)]">
        <ul className={`flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-scrolling-${direction}`}>
            {items.map((tech) => (
            <li key={tech.name} className="flex-shrink-0">
                <Link href={tech.href} target="_blank" rel="noopener noreferrer">
                    <Image src={tech.iconSrc} alt={tech.name} width={48} height={48} className="h-12 w-auto filter grayscale hover:grayscale-0 transition-all duration-300" />
                </Link>
            </li>
            ))}
        </ul>
        <ul className={`flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-scrolling-${direction}`} aria-hidden="true">
            {items.map((tech) => (
            <li key={tech.name + '-clone'} className="flex-shrink-0">
                 <Link href={tech.href} target="_blank" rel="noopener noreferrer">
                    <Image src={tech.iconSrc} alt={tech.name} width={48} height={48} className="h-12 w-auto filter grayscale hover:grayscale-0 transition-all duration-300" />
                </Link>
            </li>
            ))}
        </ul>
  </div>
);


export default function HomePage() {
  const footerLinks = [
    { name: 'Contact', icon: <Mail className="h-5 w-5" />, href: '/contact' },
    { name: 'About', icon: <User className="h-5 w-5" />, href: '/about' },
    { name: 'Back to Top', icon: <ArrowUp className="h-5 w-5" />, action: () => window.scrollTo({ top: 0, behavior: 'smooth' }) },
  ];

  function onSplineLoad(spline: Spline) {
    const obj = spline.findObjectByName('Gameboy');
    if (obj) {
      // Start the animation by name
      spline.emitEvent('mouseDown', obj.name);
    }
  }
  
  return (
    <>
      <div className="flex flex-col flex-grow bg-background">
        {/* Hero Section */}
        <AnimateOnScroll className="text-center h-[calc(100vh-80px)] min-h-[700px] flex flex-col justify-center items-center bg-grid-pattern relative">
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-background" />
          <div className="z-10">
            <motion.div
              className="relative mb-8"
              initial={{ opacity: 0, scale: 0.8, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.2, ease: [0.25, 1, 0.5, 1] }}
            >
              <Image
                src="https://i.imgur.com/TsFpBse.png"
                alt="User avatar"
                width={160}
                height={160}
                className="rounded-full border-4 border-primary shadow-xl object-cover mx-auto filter saturate-125"
                data-ai-hint="avatar illustration"
                priority
              />
            </motion.div>
            <motion.h1
              className="text-4xl sm:text-5xl md:text-6xl font-extrabold text-foreground mb-6 tracking-tighter"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.4, ease: [0.25, 1, 0.5, 1] }}
            >
              AI/Software Engineer
            </motion.h1>
            <motion.p
              className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto mb-10"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.6, ease: [0.25, 1, 0.5, 1] }}
            >
              Exploring the intersection of code, emotion, and imagination. I build web applications and create digital art that tells a story.
            </motion.p>
            <motion.div
              className="flex flex-wrap justify-center gap-4"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.8, ease: [0.25, 1, 0.5, 1] }}
            >
              <Button asChild size="lg">
                <Link href="/projects">
                  View My Work <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg">
                <Link href="/contact">
                  Get In Touch <Mail className="ml-2 h-5 w-5" />
                </Link>
              </Button>
            </motion.div>
          </div>
        </AnimateOnScroll>
        
        {/* Featured Projects Section */}
        <SectionContainer id="featured-work" className="!py-24 md:!py-32">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground">Featured Projects</h2>
            <p className="text-muted-foreground mt-3 max-w-2xl mx-auto">A curated selection of my projects, showcasing a blend of technical skill and creative vision.</p>
          </div>
          <ProjectShowcase projects={featuredProjects} />
        </SectionContainer>
        
        {/* Call to Action Section */}
        <SectionContainer id="contact-cta" className="!pt-0">
          <div className="text-center p-8 md:p-12">
             <h2 className="text-3xl md:text-4xl font-bold text-primary">Have a Project in Mind?</h2>
             <p className="text-muted-foreground mt-3 max-w-xl mx-auto">I'm always open to discussing new projects, creative ideas, or opportunities to be part of an ambitious vision. Let's create something amazing together.</p>
              <Button asChild size="lg" className="mt-8">
                <Link href="/contact">
                  Contact Me <Mail className="ml-2 h-5 w-5" />
                </Link>
              </Button>
          </div>
        </SectionContainer>
        
        {/* Old Spline Model Section - now replaced by showcase */}
        <SectionContainer id="spline-test">
              <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-foreground">My Game Stack</h2>
              <p className="text-muted-foreground mt-3 max-w-2xl mx-auto">An interactive 3D model representing the games I enjoy.</p>
              </div>
              <div className="relative h-[500px] md:h-[700px] w-full mx-auto rounded-lg overflow-hidden bg-muted/20 min-h-[500px]">
                  <SplineModel 
                    sceneUrl="https://prod.spline.design/wl4X9XbiCMDi6bUv/scene.splinecode" 
                    scrollable={false}
                    onLoad={onSplineLoad}
                  />
              </div>
        </SectionContainer>

         {/* Skills Section */}
        <SectionContainer id="skills">
           <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground">Skills & Expertise</h2>
            <p className="text-muted-foreground mt-3 max-w-2xl mx-auto">The tools and technologies I use to bring ideas to life.</p>
          </div>
          <div className="space-y-8">
              <ScrollingTechRow items={technologies.slice(0, Math.ceil(technologies.length / 2))} />
              <ScrollingTechRow items={technologies.slice(Math.ceil(technologies.length / 2))} direction="right" />
          </div>
          <div className="text-center mt-12">
              <Button asChild size="lg">
                <Link href="/about">
                  View All Skills <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
            </div>
        </SectionContainer>

        {/* 3D Model Showcase */}
         <SectionContainer id="spline-showcase">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground">3D Model Showcase</h2>
            <p className="text-muted-foreground mt-3 max-w-2xl mx-auto">A collection of my 3D creations. Use the arrows to navigate.</p>
          </div>
          <div className="hidden md:block">
            <SplineShowcase models={splineModels} />
          </div>
          <div className="block md:hidden">
            <Card className="border-border bg-card">
              <CardContent className="p-6 text-center">
                <Monitor className="h-12 w-12 mx-auto text-primary mb-4" />
                <h3 className="text-xl font-semibold text-foreground">3D Showcase Available on Desktop</h3>
                <p className="text-muted-foreground mt-2">
                  This interactive 3D model showcase is best experienced on a larger screen. Please view this page on a desktop or laptop to explore the models.
                </p>
              </CardContent>
            </Card>
          </div>
        </SectionContainer>
      </div>
      <footer className="py-16 bg-background">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-2xl font-bold text-foreground mb-4">You've reached the edge of this world.</h2>
          <p className="text-muted-foreground mb-8">What will you do now?</p>
          <div className="flex justify-center gap-4">
            <Button variant="outline" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>
              <ArrowUp className="mr-2 h-4 w-4" /> Return to Top
            </Button>
            <Button asChild>
              <Link href="/projects">
                <Compass className="mr-2 h-4 w-4" /> Explore More
              </Link>
            </Button>
          </div>
          <p className="text-xs text-muted-foreground mt-12">
            &copy; {new Date().getFullYear()} DeepTerrorGG. All Rights Reserved.
          </p>
        </div>
      </footer>
    </>
  );
}

    